language: node_js
node_js:
  - 7
deploy:
  provider: heroku
  api_key:
    secure: sL7Flibm5URD+cxQsSjRtCAP7kibbGXa0gqMbICsEjNwMGDMOnnTb3ya3zMQT5ZF0LJknlkL8thjxhunC8dzqPB4t/nzhPqm5AQkE+jujU696m5PgbPtbDbNoJweZZZS6kG5obCymci3qYSo3HZoCfUWfzCowYauMow1JMz9f8iAbkNb2YNl3EC28TIEqJT+COZLrgj3GNKAt64WMEZhMC4CWUshsDcmSGO86+YCuWL/g0qWzER34ilD4jvCvCNjm06zQNt8O1iPWqMjW98now9F6Gac/2nv8yb3tQ4p54mpqKC3VuUU9Nbq7Eb/Mz6walTzJLy8K68gjMdnJCUS4VCswNOfMrbiNlXwc2nt/FAVImpFCNhaaU4ZqT96nK9c0Y45M9KHKCKeKFC2XLlpEtNWo475JWvwRFL8kldOEHVWTOMPQrZwio/x7uxp3zwaBIHCCvi+wRL4iuFUjsyNxT+oe0mLF0eFZ8aMzKRtFda73b6pEfboBDVXq4VAKkBHlOm3SF845CdiJSXzV2d6kIUg+uUaPeKSewhlWSlThkMVk94FkfvjQ406/Gf2rVPIVTRQ0VKtCGdzYpPILLPogmMMl0s25BLsCz3bTjRvG4z0CJUoi2JJpZK7I4OBaL+alZFupoGXHYCFqQM/71SpLfF8g+HGZNpuWbdH/+lw67w=
  app: ist-calcv2
